### ISSUE TITLE
Downloading courses where 'pages ' has been disabled.

### ISSUE THREAD

**Issue by iamashwin99** [Ysgorg/canvas-lms-downloader#3]
When I try to download a course (xyz) I'm currently enrolled  I get 
```
[401 Unauthorized] https://canvas.instructure.com/api/v1/courses/xyz/files q
uery:{"per_page":999999}
[404 Not Found] https://canvas.instructure.com/api/v1/courses/xyz/pages quer
y:{"per_page":999999}
TypeError [ERR_INVALID_ARG_TYPE]: The "urlObject" argument must be one of type O
bject or string. Received type undefined
    at urlFormat (url.js:544:11)
    at new Request (/root/canvas-lms-downloader/node_modules/superagent/lib/node
/index.js:164:38)
    at request (/root/canvas-lms-downloader/node_modules/superagent/lib/node/ind
ex.js:67:10)
    at Object.request.<computed> [as get] (/root/canvas-lms-downloader/node_modu
les/superagent/lib/node/index.js:1300:15)
    at /root/canvas-lms-downloader/build/index.js:143:30
    at step (/root/canvas-lms-downloader/build/index.js:44:23)
    at Object.next (/root/canvas-lms-downloader/build/index.js:25:53)
    at /root/canvas-lms-downloader/build/index.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/root/canvas-lms-downloader/build/index.js:15:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I think this error is to do with 'pages' section disabled in the course ( When I try https://canvas.instructure.com/courses/xyz/pages on my browser, I get a "That page has been disabled for this course" notice)

Is there any workaround for this?

**Comment by Ysgorg** [comment]
The 401 Unauthorized error is a rejection from the server and can't be worked around by the client unfortunately. If you get a 401 error it's because the admins don't grant access to the resource. You could ask the admins of the course page to unlock it.

**Comment by iamashwin99** [comment]
I commented out pages files and announcement download and kept only module section download (which I know is accessible ) I still get this error
```
TypeError [ERR_INVALID_ARG_TYPE]: The "urlObject" argument must be one of type O
bject or string. Received type undefined
    at urlFormat (url.js:544:11)
    at new Request (/root/canvas-lms-downloader/node_modules/superagent/lib/node
/index.js:164:38)
    at request (/root/canvas-lms-downloader/node_modules/superagent/lib/node/ind
ex.js:67:10)
    at Object.request.<computed> [as get] (/root/canvas-lms-downloader/node_modu
les/superagent/lib/node/index.js:1300:15)
    at /root/canvas-lms-downloader/build/index.js:143:30
    at step (/root/canvas-lms-downloader/build/index.js:44:23)
    at Object.next (/root/canvas-lms-downloader/build/index.js:25:53)
    at /root/canvas-lms-downloader/build/index.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/root/canvas-lms-downloader/build/index.js:15:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by bmelanman** [comment]
Hello everyone, sorry to message a year old thread, but I was able to fix this issue! Within the `downloadModules()` on line [170](https://github.com/Ysgorg/canvas-lms-downloader/blob/df2c14dbf00d26fc899af032ec92e6d604ab1a14/src/index.ts#L170), the module item's URL is used to get the "thing" that the module item contains. 

The root of the issue lies in that there are module items that do not inherently have URLs attached to them. So with that said, all you need to do is simply add the following line of code before the `getJson()` call on line 170. This will skip any module items that aren't files or something else that could be downloaded. 

`if (!item.url) continue; // New Code`
`const thing = await getJson(item.url) // Existing code`

@Ysgorg This is a fairly small change, so I won't both with a pull request and such. Feel free to just implement it. 
Hope this helps!

**Comment by Ysgorg** [comment]
I implemented the suggested fix, thanks!
